### ISSUE TITLE
Decide if we do history or not

### ISSUE THREAD

**Issue by evarayHEIG** [Plant-keeper/PlantKeeper#18]

**Comment by evarayHEIG** [comment]
pour moi c'est mort de chez mort

**Comment by ludelafo** [comment]
Allez à l'essentiel et tentez à vous reposer quand-même ! :)

**Comment by evarayHEIG** [comment]
> Allez à l'essentiel et tentez à vous reposer quand-même ! :)
haha merci, on va essayer

**Comment by evarayHEIG** [comment]
## Résumé de la discussion teams

Non, on n'a pas le temps. C'est surtout long de faire des graphes et de changer le schéma de la db mtn. On préfère peaufiner ce qu'on a déjà. On listera cette idée dans les "idées d'amélioration futures".
